[package]
name = "os_blog"
version = "0.1.0"
edition = "2018"

[dependencies]
bootloader = "0.9"
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = "0.5.2"
volatile = "0.2.6"

[[bin]]
name = "os_blog"
path = "src/main.rs"
test = false
doctest = false
bench = false
